service: heartland-api-v3
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 512
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    FLOW_ACCESS_NODE: ${env:FLOW_ACCESS_NODE}
    HEART_CONTRACT_ADDRESS: ${env:HEART_CONTRACT_ADDRESS}
    JWT_SECRET: ${env:JWT_SECRET}
    # SQS resources
    TRANSACTION_QUEUE_URL:
      Ref: TransactionQueue
  # logs:
  #   httpApi: true
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:GetQueueUrl
      Resource:
        - !GetAtt TransactionQueue.Arn
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:DescribeLogStreams
        - logs:FilterLogEvents
      Resource: '*'

plugins:
  - serverless-offline

# Lambda Layers定義 (最適化版)
layers:
  # 統合ブロックチェーン Layer (~160MB)
  blockchainLayer:
    path: layers/blockchain
    name: ${self:service}-blockchain-${self:provider.stage}
    description: Unified blockchain layer - Flow SDK, viem, WalletConnect
    compatibleRuntimes:
      - nodejs22.x
    retain: false

  # AWS SDK Layer (~19MB)
  awsSdkLayer:
    path: layers/aws-sdk
    name: ${self:service}-aws-sdk-${self:provider.stage}
    description: AWS SDK dependencies
    compatibleRuntimes:
      - nodejs22.x
    retain: false

  # Web依存関係 Layer (~15MB)
  webDepsLayer:
    path: layers/web-deps
    name: ${self:service}-web-deps-${self:provider.stage}
    description: Web dependencies - Express, Swagger
    compatibleRuntimes:
      - nodejs22.x
    retain: false

functions:
  # Main API application
  app:
    handler: dist/lambda.handler
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
      - { Ref: BlockchainLayerLambdaLayer } # Flow SDK統合
      - { Ref: WebDepsLayerLambdaLayer }
    events:
      - httpApi: '*'

  # SQS Transaction Worker
  transactionWorker:
    handler: dist/workers/transactionWorker.handler
    timeout: 300
    memorySize: 1024
    layers:
      - { Ref: AwsSdkLayerLambdaLayer }
      - { Ref: BlockchainLayerLambdaLayer } # WalletConnect含む統合Layer
    events:
      - sqs:
          arn: !GetAtt TransactionQueue.Arn
          batchSize: 1
    environment:
      ADMIN_PRIVATE_KEY: ${env:ADMIN_PRIVATE_KEY}
      ADMIN_ADDRESS: ${env:ADMIN_ADDRESS}

  # Job Status Cleanup (runs daily)
  jobCleanup:
    handler: dist/workers/jobCleanup.handler
    timeout: 60
    layers:
      - { Ref: AwsSdkLayerLambdaLayer } # CloudWatch Logs用のみ
    events:
      - schedule: rate(1 day)

  # Swagger UI hosting
  swaggerUI:
    handler: dist/swagger.handler
    layers:
      - { Ref: WebDepsLayerLambdaLayer } # Swagger UI用
    events:
      - httpApi:
          path: /docs
          method: get
      - httpApi:
          path: /docs/{proxy+}
          method: get

resources:
  Resources:
    # SQS Queue for Transaction Processing
    TransactionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-transaction-queue-${self:provider.stage}
        VisibilityTimeout: 360
        MessageRetentionPeriod: 1209600 # 14 days
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TransactionDLQ.Arn
          maxReceiveCount: 3

    # Dead Letter Queue for failed transactions
    TransactionDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-transaction-dlq-${self:provider.stage}
        MessageRetentionPeriod: 1209600 # 14 days

custom:
  serverless-offline:
    httpPort: 3000
    noAuth: true
    resourceRoutes: true

package:
  # 自動的に開発依存関係を除外（Serverless Framework v4の機能）
  excludeDevDependencies: true

  patterns:
    # 必要なファイルのみを明示的に含める
    - 'dist/**'
    - 'build/swagger.json'
    - 'package.json'

    # 不要なファイルを明示的に除外
    - '!src/**'
    - '!tests/**'
    - '!coverage/**'
    - '!*.md'
    - '!.env*'
    - '!.cursor*'
    - '!.git*'
    - '!tsconfig.json'
    - '!tsoa.json'
    - '!jest.config.js'
    - '!eslint.config.js'
    - '!.prettier*'
    - '!scripts/**'
    - '!transactions/**'
    - '!contracts/**'
    - '!docs/**'
    - '!flow.json'
    - '!setup-minter-role.js'
    - '!test-keys.js'
    - '!sample.env'

    # 開発依存関係のnode_modulesを除外
    - '!node_modules/@types/**'
    - '!node_modules/@typescript-eslint/**'
    - '!node_modules/@eslint/**'
    - '!node_modules/eslint/**'
    - '!node_modules/prettier/**'
    - '!node_modules/jest/**'
    - '!node_modules/ts-jest/**'
    - '!node_modules/typescript/**'
    - '!node_modules/serverless/**'
    - '!node_modules/serverless-offline/**'
