/**
 * Express application configuration with tsoa integration
 *
 * @description This file configures the Express application with tsoa-generated routes,
 * middleware, and Flow blockchain integration for the Heart Token API.
 *
 * @author Heart Token API Team
 * @since 1.0.0
 */

import express from 'express';
import type { Express } from 'express';
import swaggerUi from 'swagger-ui-express';

/**
 * Express application instance
 *
 * @description Main Express application configured with middleware, routes, and documentation.
 * This app will be used by the Lambda handler to process HTTP requests.
 *
 * @example
 * ```typescript
 * import { app } from './app';
 * // Use app in Lambda handler or for local development
 * ```
 */
export const app: Express = express();

/**
 * Configure Express middleware
 *
 * @description Sets up essential middleware for JSON parsing, CORS, and logging.
 */
const configureMiddleware = (): void => {
  // JSON parsing middleware
  app.use(express.json({ limit: '10mb' }));
  app.use(express.urlencoded({ extended: true }));

  // CORS middleware
  app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type,Authorization');

    if (req.method === 'OPTIONS') {
      res.sendStatus(200);
    } else {
      next();
    }
  });

  // Request logging middleware
  app.use((req, res, next) => {
    console.log(`${new Date().toISOString()} - ${req.method} ${req.path}`);
    next();
  });
};

/**
 * Configure API routes
 *
 * @description Sets up tsoa-generated routes and health check endpoints.
 * The actual routes will be generated by tsoa based on controller decorators.
 */
const configureRoutes = (): void => {
  // Health check endpoint
  app.get('/health', (req, res) => {
    res.json({
      success: true,
      message: 'Flow Heart Token API is healthy',
      timestamp: new Date().toISOString(),
      version: '1.0.0',
    });
  });

  // API info endpoint
  app.get('/api/info', (req, res) => {
    res.json({
      success: true,
      data: {
        name: 'Flow Heart Token Control API',
        version: '1.0.0',
        description:
          'TypeScript-based Serverless API for Flow Heart Token Contract',
        blockchain: 'Flow Network (Testnet)',
        contractAddress:
          process.env.HEART_CONTRACT_ADDRESS || '0x58f9e6153690c852',
      },
      timestamp: new Date().toISOString(),
    });
  });

  // TODO: Add tsoa-generated routes
  // These will be automatically generated when running: pnpm run tsoa:routes
  // import { RegisterRoutes } from '../build/routes';
  // RegisterRoutes(app);
};

/**
 * Configure API documentation
 *
 * @description Sets up Swagger UI for interactive API documentation.
 * Uses the OpenAPI specification generated by tsoa.
 */
const configureDocumentation = (): void => {
  try {
    // TODO: Load generated swagger.json after running tsoa:spec
    // const swaggerDocument = require('../build/swagger.json');

    // For now, provide basic documentation structure
    const basicSwaggerDoc = {
      openapi: '3.0.0',
      info: {
        title: 'Flow Heart Token Control API',
        version: '1.0.0',
        description:
          'TypeScript-based Serverless API for Flow Heart Token Contract',
      },
      servers: [
        {
          url: 'https://api.example.com',
          description: 'Production server',
        },
        {
          url: 'http://localhost:3000',
          description: 'Development server',
        },
      ],
      paths: {
        '/health': {
          get: {
            summary: 'Health check endpoint',
            responses: {
              '200': {
                description: 'API health status',
              },
            },
          },
        },
      },
    };

    app.use('/docs', swaggerUi.serve, swaggerUi.setup(basicSwaggerDoc));

    console.log('API documentation available at: /docs');
  } catch (error) {
    console.warn('Could not load API documentation:', error);
  }
};

/**
 * Configure error handling
 *
 * @description Sets up global error handling middleware for the application.
 */
const configureErrorHandling = (): void => {
  // 404 handler - catch all unmatched routes
  app.use((req, res) => {
    res.status(404).json({
      success: false,
      error: {
        code: 'NOT_FOUND',
        message: `Route ${req.method} ${req.originalUrl} not found`,
      },
      timestamp: new Date().toISOString(),
    });
  });

  // Global error handler
  app.use(
    (
      error: Error,
      req: express.Request,
      res: express.Response,
      next: express.NextFunction
    ) => {
      console.error('Unhandled error:', error);

      res.status(500).json({
        success: false,
        error: {
          code: 'INTERNAL_SERVER_ERROR',
          message: 'An unexpected error occurred',
          details:
            process.env.NODE_ENV === 'development' ? error.message : undefined,
        },
        timestamp: new Date().toISOString(),
      });
    }
  );
};

/**
 * Initialize the Express application
 *
 * @description Configures all middleware, routes, documentation, and error handling.
 */
const initializeApp = (): void => {
  configureMiddleware();
  configureRoutes();
  configureDocumentation();
  configureErrorHandling();

  console.log('Flow Heart Token API initialized successfully');
};

// Initialize the application
initializeApp();
